### ISSUE TITLE
Precondition Failed ...

### ISSUE THREAD

**Issue by SandyWalsh** [MattDietz/yagi#4]
amqplib.client_0_8.exceptions.AMQPChannelException: (406, u"PRECONDITION_FAILED - cannot redeclare exchange 'nova' in vhost '/' with different type, durable, internal or autodelete value", (40, 10), 'Channel.exchange_declare')

http://paste.openstack.org/show/1758/

When running in an environment where Openstack Nova has already been running.

**Comment by SandyWalsh** [comment]
Still getting this ... is there a change required to the .conf file?

**Comment by MattDietz** [comment]
What did you set your exchange types to? Mine looks like:

[consumer:notifications.info]
apps = yagi.handler.pubsubhubbub_handler.PubSubHubBubHandler, yagi.handler.redis_handler.RedisHandler
exchange = nova
exchange_type = topic
routing_key = notifications.info
durable = False
max_messages = 100

**Comment by SandyWalsh** [comment]
Same ...

[consumer:notifications.info]
apps = yagi.handler.pubsubhubbub_handler.PubSubHubBubHandler, yagi.handler.redis_handler.R    edisHandler
exchange = nova
exchange_type = topic
routing_key = notifications.info
durable = False
max_messages = 100

**Comment by SandyWalsh** [comment]
If I reset rabbit (flushing the nova exchange), then Nova fails with the same error when I attempt to do something:

http://paste.openstack.org/show/1824/

**Comment by SandyWalsh** [comment]
This time it worked for me ... odd

sudo rabbmitmqctl app-stop
sudo rabbmitmqctl reset

# confirm exchanges and queues are nuked

sudo rabbmitmqctl app-start
